# Generated by Django 5.0.5 on 2024-05-21 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='anoPublicação',
            new_name='anoPublicacao',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='numeroEdição',
            new_name='numeroEdicao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='usuariocustomizado',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='usuariocustomizado',
            name='foto',
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.CharField(blank=True, max_length=5000, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='livros',
            name='autorFK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='autorLivro', to='app.autor'),
            preserve_default=False,
        ),
    ]
